# Generated by Django 6.0.4 on 2026-05-14 10:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_moderator', models.BooleanField(default=False, verbose_name='Модератор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалён'), ('formed', 'Сформирован'), ('completed', 'Завершён'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('formed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма')),
                ('delivery_address', models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес доставки')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Комментарии')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='moderated_requests', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('cas', models.CharField(max_length=50, unique=True, verbose_name='CAS номер')),
                ('description', models.TextField(default='', verbose_name='Краткое описание')),
                ('full_description', models.TextField(default='', verbose_name='Полное описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('unit', models.CharField(default='кг', max_length=20, verbose_name='Единица измерения')),
                ('image_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ключ изображения в MinIO')),
                ('video_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ключ видео в MinIO')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('molecular_weight', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Молекулярная масса')),
                ('storage_conditions', models.CharField(default='', max_length=500, verbose_name='Условия хранения')),
                ('shelf_life', models.IntegerField(default=24, verbose_name='Срок годности (месяцев)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=200, verbose_name='Производитель')),
                ('country_of_origin', models.CharField(blank=True, default='', max_length=100, verbose_name='Страна производства')),
                ('purity', models.DecimalField(decimal_places=2, default=99.0, max_digits=5, verbose_name='Чистота (%)')),
                ('pharmacopoeia', models.CharField(default='USP, EP', max_length=50, verbose_name='Фармакопея')),
                ('storage_temperature', models.CharField(default='15-25°C', max_length=50, verbose_name='Температура хранения')),
            ],
            options={
                'verbose_name': 'Субстанция',
                'verbose_name_plural': 'Субстанции',
                'db_table': 'substances',
                'indexes': [models.Index(fields=['name'], name='substances_name_548c7f_idx'), models.Index(fields=['cas'], name='substances_cas_bd33b4_idx'), models.Index(fields=['is_active'], name='substances_is_acti_a3f6f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество')),
                ('unit', models.CharField(default='кг', max_length=20, verbose_name='Единица измерения')),
                ('mm_value', models.CharField(blank=True, default='', max_length=200, verbose_name='Поле м-м')),
                ('order_number', models.IntegerField(default=1, verbose_name='Порядковый номер')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главная позиция')),
                ('item_comment', models.CharField(blank=True, default='', max_length=500, verbose_name='Комментарий к позиции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('calculated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Результат вычислений')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='substances.request', verbose_name='Заявка')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='request_items', to='substances.substance', verbose_name='Субстанция')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявок',
                'db_table': 'request_items',
            },
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['user', 'status'], name='requests_user_id_2e1dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status'], name='requests_status_58d546_idx'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('user', 'status'), name='unique_user_draft'),
        ),
        migrations.AddIndex(
            model_name='requestitem',
            index=models.Index(fields=['request', 'is_active'], name='request_ite_request_b097de_idx'),
        ),
        migrations.AddIndex(
            model_name='requestitem',
            index=models.Index(fields=['substance', 'is_active'], name='request_ite_substan_4fa475_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requestitem',
            unique_together={('request', 'substance', 'is_active')},
        ),
    ]
