FROM python:3.14-slim

WORKDIR /app

# системные зависимости
RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# python зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# код проекта
COPY . .

# порт django
EXPOSE 8000

# запуск django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
